### ISSUE TITLE
Disable caching for tests?

### ISSUE THREAD

**Issue by Clete2** [jaemk/cached#130]
Is there an easy way to disable caching for testing purposes?

A simple example is below; where I cache a URL. The second test always fails because the result is still cached from the first test. More complex examples also fail due to caching.

```rust
use cached::proc_macro::cached;

#[cached]
fn url() -> String {
    std::env::var("hostname").unwrap_or_else(|_| String::from("some.hostname"))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn url_default() {
        std::env::remove_var("hostname");
        assert_eq!(url(), "some.hostname");
    }

    #[test]
    fn url_override() {
        std::env::set_var("hostname", "some.other.hostname");
        assert_eq!(url(), "some.other.hostname");
    }
}
```

**Comment by LikeLakers2** [comment]
You can use `#[cfg_attr()]` for this purpose. As an example:

```rust
#[cfg_attr(
	not(test),
	cached
)]
pub fn load_as_arc(i: i64) -> Arc<i64> {
	Arc::new(i)
}
```

will only cache the results of the function if you are *not* compiling something for tests.

*That said,* I wouldn't used cached in the example code you gave, as cached will never be able to detect the change in an environmental variable. It only sees that you're calling `url()` with the same parameters as before (in this case, none at all), and assumes that you want the same result back.

**Comment by Clete2** [comment]
That's exactly what I needed @LikeLakers2; thank you! I agree with the sentiment of not caching it; what I provided was just an example. In reality I'm caching things like AWS SDK clients which are relatively expensive to create.
