### ISSUE TITLE
Upgrade redis to 0.22

### ISSUE THREAD

**Issue by jqnatividad** [jaemk/cached#131]
and possibly use the optional `ahash` feature which gives a 7-10% performance bump:

https://github.com/redis-rs/redis-rs/blob/1b3f8ad0e1ebfe4e7d81563559c1e743acc5e806/redis/src/lib.rs#L60

**Comment by jaemk** [comment]
updated in v`0.40.0`. The `ahash` feature can be enabled with the `redis_ahash` feature
