### ISSUE TITLE
Add feature for usage of `redis::aio::ConnectionManager` to help to recover from redis server restarts

### ISSUE THREAD

**Issue by a-nickol** [jaemk/cached#154]
[`redis`](https://docs.rs/redis/latest/redis/) library offers a feature `connection-manager` to help to recover from a closed [`MultiplexedConnection`](https://docs.rs/redis/latest/redis/aio/struct.MultiplexedConnection.html).

A [connection manager](https://docs.rs/redis/latest/redis/aio/struct.ConnectionManager.html) can be used instead of mulitplexed connection to recover from various error scenarios like network issues, or server restarts.

It would be super to integrate this into the `cached` library as a feature, too.

**Comment by omid** [comment]
@jaemk @a-nickol so it means we can close this?
