### ISSUE TITLE
`async_once` is unsound

### ISSUE THREAD

**Issue by Jules-Bertholet** [jaemk/cached#156]
`cached` depends on the `async_once` crate, which [suffers from a data race](https://github.com/hjiayz/async_once/issues/5). There are many alternatives in the ecosystem that provide similar functionality. Among them:

- [`async-once-cell`](https://github.com/danieldg/async-once-cell)
- [`tokio::sync::OnceCell`](https://docs.rs/tokio/latest/tokio/sync/struct.OnceCell.html)
- [`async-static`](https://github.com/liangyongrui/async_static)
- My own [`async-lazy`](https://github.com/Jules-Bertholet/async-lazy)

**Comment by omid** [comment]
It's been removed in this PR, which has been just merged
Please check master again

https://github.com/jaemk/cached/pull/153

**Comment by jaemk** [comment]
I'll release a new version with these changes shortly. I got pulled away earlier today
