### ISSUE TITLE
Why does `DiskCache` need to impl `Display`?

### ISSUE THREAD

**Issue by IgnisDa** [jaemk/cached#207]
Looking at the docs for DiskCache [here](https://docs.rs/cached/latest/cached/stores/struct.DiskCache.html#impl-DiskCache%3CK,+V%3E), it defines:

```rs
impl<K, V> DiskCache<K, V>
where
    K: Display,
    V: Serialize + DeserializeOwned
```

Is there any particular reason why it needs to implement `Display`?

**Comment by IgnisDa** [comment]
If possible, could this be removed completely? If not, atleast be gated behind a feature?

**Comment by IgnisDa** [comment]
@jaemk Could you take a look at this please?

**Comment by omid** [comment]
@IgnisDa I think it'll move it faster, if you create a PR.

**Comment by IgnisDa** [comment]
I tried to do it here but it did not work: https://github.com/IgnisDa/cached/tree/remove-display-trait

**Comment by omid** [comment]
@IgnisDa I think _just_ replacing `Display` with `ToString` will do the job.

**Comment by IgnisDa** [comment]
@omid That still does not solve the problem since

![image](https://github.com/jaemk/cached/assets/60938164/8b4a3147-0f05-47fd-8872-35d1d7875d48)

**Comment by IgnisDa** [comment]
@omid Made a PR.
