### ISSUE TITLE
Published version 0.5.0 is actually missing `cached_control`

### ISSUE THREAD

**Issue by yongqli** [jaemk/cached#5]
See https://docs.rs/cached/0.5.0/cached/#macros

**Comment by jaemk** [comment]
Looks like I didn't publish a new version since it's been added. I'll do a new one later today

**Comment by jaemk** [comment]
https://github.com/jaemk/cached/commit/0ed46ce9d6754da572d38617547a7b6b421007a9
https://docs.rs/cached/0.6.0/cached/
