### ISSUE TITLE
Cache impl functions

### ISSUE THREAD

**Issue by rivertam** [jaemk/cached#6]
Is this even possible? Would love to be able to put cached functions inline with an impl rather than having to rely on an external implementation.

**Comment by jaemk** [comment]
No, unfortunately it's not possible. The cached macros all expand to a lazy_static block defining a cache object and the function specified in the macro, and that lazy_static block can't live in the impl.

**Comment by rivertam** [comment]
Okay. Unfortunate. Thanks for letting me know. =)
