### ISSUE TITLE
Support TTL for the cache

### ISSUE THREAD

**Issue by omid** [jaemk/cached#61]
Is there any plan to support TTL for the cached value in the macro?

```
#[cached(size=100, ttl=10)]
fn keyed(a: String, b: String) -> usize {
    let size = a.len() + b.len();
    sleep(Duration::new(size as u64, 0));
    size
}
```

PS: Or we already have this feature?!

**Comment by omid** [comment]
OK, I think I found it:

```
#[cached(size=100, time=10)]
fn keyed(a: String, b: String) -> usize {
    let size = a.len() + b.len();
    sleep(Duration::new(size as u64, 0));
    size
}
```

If it's correct, I think it's better to have some examples of this. And also mentioning all possible arguments in the README.md.

**Comment by jaemk** [comment]
Yes, that's correct. The proc macro could definitely use some more documentation. One thing to keep in mind here is that the implementation of a LRU-Timed cache is still in PR #54 so passing `time` will use a `cached::TimedCache` https://github.com/jaemk/cached/blob/4f2b406b2a4754bdc139693875982348063e3dfc/cached_proc_macro/src/lib.rs#L173
