### ISSUE TITLE
Cache without key

### ISSUE THREAD

**Issue by macthestack** [jaemk/cached#77]
What's the idiomatic way to express a cache on a fn with parameters but without a "key"?

```
#[cached(time = 5, key = "&str", convert = r#"{ "" }"#)]
async fn cached_health(db_pool: DBPool) -> Result<(), Error> {
```

The above works but it looks a bit dirty.

**Comment by jaemk** [comment]
Yeah, that's currently the best way - using `bool` and `true` might be more obvious to read though. We could probably add an arg to `cached` to have it set `bool` and `true` automatically for you. I'm not sure what the best way to express that would be... 
```
#[cached(time = 5, key = None)]
#[cached(time = 5, no_key)]
#[cached(time = 5, keyless)]
#[cached(time = 5, always)]
```

**Comment by EvanCarroll** [comment]
Not sure of the right syntax @jaemk but I tried

    #[cached(time = 5, key = "bool", convert = r#"{ true }"#)]

I'm getting a lot of errors with this though,


```rust
error[E0308]: mismatched types
  --> src/main.rs:11:1
   |
11 | #[cached(time = 5, key = "bool", convert = r#"{ true }"#)]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected enum `std::result::Result`, found reference
   |
   = note:   expected enum `std::result::Result<Vec<Alert>, reqwest::Error>`
           found reference `&std::result::Result<Vec<Alert>, reqwest::Error>`
   = note: this error originates in an attribute macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0599]: no method named `clone` found for enum `std::result::Result<Vec<Alert>, reqwest::Error>` in the current scope
   --> src/main.rs:11:1
    |
11  |   #[cached(time = 5, key = "bool", convert = r#"{ true }"#)]
    |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ method not found in `std::result::Result<Vec<Alert>, reqwest::Error>`
    | 
   ::: /home/ecarroll/.cargo/registry/src/github.com-1ecc6299db9ec823/reqwest-0.11.1/src/error.rs:12:1
    |
12  |   pub struct Error {
    |   ---------------- doesn't satisfy `reqwest::Error: Clone`
    |
    = note: the method `clone` exists but the following trait bounds were not satisfied:
            `Vec<Alert>: Clone`
            which is required by `std::result::Result<Vec<Alert>, reqwest::Error>: Clone`
            `reqwest::Error: Clone`
            which is required by `std::result::Result<Vec<Alert>, reqwest::Error>: Clone`
    = note: this error originates in an attribute macro (in Nightly builds, run with -Z macro-backtrace for more info)


```

**Comment by jaemk** [comment]
I believe the error you're getting is because you need to add a `result = true`. The following
```
#[cached(time = 5, key = "bool", convert = r#"{ true }"#, result = true)]
async fn cached_test(s: String) -> std::result::Result<Vec<String>, &'static dyn std::error::Error> {
    Ok(vec![s])
}


println!("{:?}", cached_test("a".to_string()).await);
println!("{:?}", cached_test("definitely not a".to_string()).await);
```
prints out
```
Ok(["a"])
Ok(["a"])
```

**Comment by macthestack** [comment]
I actually tried `#[cached(time = 5, key = None)]` at first because it felt intuitive.

However, I'm starting to think that this is just an edge case of "I want to ingore this parameters" or "I just care about these parameters" which is already covered by key+convert. Maybe a more ergonomic addition would be to be able to select keys by name like:

```
#[cached(time = 5, keys = (a, b) )]
async fn something(db_pool: DBPool, a: String, b: String) -> Result<(), Error> {
```

I am not sure if that's how to do it in macro-land but it would be crystal clear to me as a user of the library. If there's a problem with mixing types I would certainly be ok with having to impl something like Hash on all keys so we get a tuple that's Hash.

Anyway, thanks for a great lib!

**Comment by jaemk** [comment]
The tough part is being able to name the type that's the cache key, so while it's not as pretty as what you have there, I think this would work. Also the proc macro is using this crate https://docs.rs/darling/0.12.2/darling/ to parse the proc macro parameters, and one of the limitations is that the arguments need to be strings

```
#[cached(time = 5, key = "(String, String)", convert = r#"{ (a, b) }"#, result = true)]
async fn cached_test(a: String, b: String) -> std::result::Result<Vec<String>, &'static dyn std::error::Error> {
    Ok(vec![a])
}
```

**Comment by gitmalong** [comment]
> I believe the error you're getting is because you need to add a `result = true`. The following
> 
> ```
> #[cached(time = 5, key = "bool", convert = r#"{ true }"#, result = true)]
> async fn cached_test(s: String) -> std::result::Result<Vec<String>, &'static dyn std::error::Error> {
>     Ok(vec![s])
> }
> 
> 
> println!("{:?}", cached_test("a".to_string()).await);
> println!("{:?}", cached_test("definitely not a".to_string()).await);
> ```
> 
> prints out
> 
> ```
> Ok(["a"])
> Ok(["a"])
> ```

That gives me
```associated `static` items are not allowedrustc```

**Comment by jaemk** [comment]
The `#[once]` macro was added back in October which I believe will do what you were asking for:
https://github.com/jaemk/cached/blob/e24d7a739dd112e8857581cb6538191fbde038f2/tests/cached.rs#L588-L594

The arguments are passed through to your logic, but there is no "key" - it's only caching a singleton associated with the function.
