### ISSUE TITLE
Revive TTL Option

### ISSUE THREAD

**Issue by itohatweb** [jaemk/cached#97]
Hey yall, so I have used this crate since a few days now and I have noticed that there is a `time` prop which can be passed to give the cached values a certain time to live before getting removed.
Now my feature request: Add an option (maybe called `reset_time` idk) which accepts a `bool` and if its `true` reset the `time` again when the same key gets accessed while the value still is in cache.

**Comment by jaemk** [comment]
Released in `0.27.0`: `time_refresh`

see https://github.com/jaemk/cached/blob/cd10eac5c754ce955148e2f79b557b9dadfa04f1/tests/cached.rs#L1012-L1050

**Comment by itohatweb** [comment]
Cool, thank you for adding this.
